### ISSUE TITLE
redmine-3.4.5-0 install failed.

### ISSUE THREAD

**Issue by walkwolf** [AlphaNodes/redmine_hedgedoc#1]
```
bash-4.2$ rake redmine:plugins:migrate RAILS_ENV=production
rake aborted!
NameError: uninitialized constant Emoji
/home/redmine/redmine-3.4.5-0/apps/redmine/htdocs/plugins/additionals/lib/additionals.rb:24:in `setup'
/home/redmine/redmine-3.4.5-0/apps/redmine/htdocs/plugins/additionals/init.rb:44:in `block in <top (required)>'
/home/redmine/redmine-3.4.5-0/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:446:in `instance_exec'
/home/redmine/redmine-3.4.5-0/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:446:in `block in make_lambda'
/home/redmine/redmine-3.4.5-0/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:192:in `block in simple'
/home/redmine/redmine-3.4.5-0/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:504:in `block in call'
/home/redmine/redmine-3.4.5-0/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:504:in `each'
/home/redmine/redmine-3.4.5-0/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:504:in `call'
/home/redmine/redmine-3.4.5-0/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/home/redmine/redmine-3.4.5-0/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:778:in `_run_prepare_callbacks'
/home/redmine/redmine-3.4.5-0/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:81:in `run_callbacks'
/home/redmine/redmine-3.4.5-0/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/reloader.rb:83:in `prepare!'
/home/redmine/redmine-3.4.5-0/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/reloader.rb:55:in `prepare!'
/home/redmine/redmine-3.4.5-0/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/application/finisher.rb:50:in `block in <module:Finisher>'
/home/redmine/redmine-3.4.5-0/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/initializable.rb:30:in `instance_exec'
/home/redmine/redmine-3.4.5-0/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/initializable.rb:30:in `run'
/home/redmine/redmine-3.4.5-0/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/initializable.rb:55:in `block in run_initializers'
/home/redmine/redmine-3.4.5-0/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/initializable.rb:54:in `run_initializers'
/home/redmine/redmine-3.4.5-0/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/application.rb:352:in `initialize!'
/home/redmine/redmine-3.4.5-0/apps/redmine/htdocs/config/environment.rb:14:in `<top (required)>'
/home/redmine/redmine-3.4.5-0/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/application.rb:328:in `require'
/home/redmine/redmine-3.4.5-0/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/application.rb:328:in `require_environment!'
/home/redmine/redmine-3.4.5-0/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/application.rb:457:in `block in run_tasks_blocks'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)

```

**Comment by alexandermeindl** [comment]
Did you follow the installation instruction? It looks to me, that you did not run bundle install.

**Comment by walkwolf** [comment]
Yes, I followed the installation instruction.
The full log is as follows.

```
bash-4.2$ bundle install --without development test
You are trying to install in deployment mode after changing
your Gemfile. Run `bundle install` elsewhere and add the
updated Gemfile.lock to version control.

If this is a development machine, remove the /home/redmine/redmine-3.4.5-0/apps/redmine/htdocs/Gemfile freeze 
by running `bundle install --no-deployment`.

the dependencies in your gemfile changed


You have added to the Gemfile:
* deface (>= 1.1.0)
* gemoji (~> 3.0.0)
* invisible_captcha
* slim-rails
* brakeman
* rubocop
* slim_lint
bash-4.2$ bundle exec rake redmine:plugins:migrate RAILS_ENV=production
rake aborted!
NameError: uninitialized constant Emoji
/home/redmine/redmine-3.4.5-0/apps/redmine/htdocs/plugins/additionals/lib/additionals.rb:24:in `setup'
/home/redmine/redmine-3.4.5-0/apps/redmine/htdocs/plugins/additionals/init.rb:44:in `block in <top (required)>'
/home/redmine/redmine-3.4.5-0/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:446:in `instance_exec'
/home/redmine/redmine-3.4.5-0/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:446:in `block in make_lambda'
/home/redmine/redmine-3.4.5-0/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:192:in `block in simple'
/home/redmine/redmine-3.4.5-0/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:504:in `block in call'
/home/redmine/redmine-3.4.5-0/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:504:in `each'
/home/redmine/redmine-3.4.5-0/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:504:in `call'
/home/redmine/redmine-3.4.5-0/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/home/redmine/redmine-3.4.5-0/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:778:in `_run_prepare_callbacks'
/home/redmine/redmine-3.4.5-0/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:81:in `run_callbacks'
/home/redmine/redmine-3.4.5-0/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/reloader.rb:83:in `prepare!'
/home/redmine/redmine-3.4.5-0/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/reloader.rb:55:in `prepare!'
/home/redmine/redmine-3.4.5-0/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/application/finisher.rb:50:in `block in <module:Finisher>'
/home/redmine/redmine-3.4.5-0/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/initializable.rb:30:in `instance_exec'
/home/redmine/redmine-3.4.5-0/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/initializable.rb:30:in `run'
/home/redmine/redmine-3.4.5-0/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/initializable.rb:55:in `block in run_initializers'
/home/redmine/redmine-3.4.5-0/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/initializable.rb:54:in `run_initializers'
/home/redmine/redmine-3.4.5-0/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/application.rb:352:in `initialize!'
/home/redmine/redmine-3.4.5-0/apps/redmine/htdocs/config/environment.rb:14:in `<top (required)>'
/home/redmine/redmine-3.4.5-0/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/application.rb:328:in `require'
/home/redmine/redmine-3.4.5-0/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/application.rb:328:in `require_environment!'
/home/redmine/redmine-3.4.5-0/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/application.rb:457:in `block in run_tasks_blocks'
/home/redmine/redmine-3.4.5-0/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/home/redmine/redmine-3.4.5-0/ruby/bin/bundle:23:in `load'
/home/redmine/redmine-3.4.5-0/ruby/bin/bundle:23:in `<main>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)
```

**Comment by alexandermeindl** [comment]
If I remove gemoji from Gemfile, I got the same error you got. This means, your Redmine installation does not respect Gemfiles from plugins. If you fix this problem, it should work.
This is nothing, what I can fix in the plugin, it is a problem with your system environment, starting process for Redmine.

**Comment by da2125** [comment]
I also get the same error and I also followed the plugin install instructions. I am using the Bitnami Redmine4 stack for Windows. This error occurs with the last 3 or 4 versions of Bitnamis Redmine3.x stacks. 
Can you be more specific on what path, or environment variable needs to be set for GEMS or RAILS or RoR? Also, I am a newbie to troubleshooting Redmine plugins so if you could also tell me if there is a command I can run to determine where Redmine would return the exiting path and how do I know what the path should be, and how to set it within Redmine - if that's what's needed, or if it just needs to be set within Windows which I can do.
Thanks Dan

**Comment by alexandermeindl** [comment]
It looks like you have to do some special command with Bitnami. 

Try:
```
cd C:\Bitnami\redmine-4.0.0-0\apps\redmine\htdocs
bundle install --without development test postgresql sqlite --no-deployment
bundle install --without development test postgresql sqlite --deployment
ruby bin/rake redmine:plugins RAILS_ENV=production
```
I tried it with Windows 10 and Bitname Redmine 4.0.0.

It is not an issue with the plugin, but with loading Gem files with Bitnami. With other Redmine plugin, which require Gem files, you have to do the same steps.

I hope, this helps you.

**Comment by da2125** [comment]
Thanks for your help, but so far still not working.  When I ran 'bundle install --without development test postgresql sqlite --no-deployment' system just hung, so I aborted the command, removed "postgresql " from the commands and re-ran them because I'm using sqlite only.
I captured the output and pasted it below. I understand this is not an issue with your plugin, but if you could give a quick look maybe you can spot something obvious, and/or see something that makes you think you could add some additional checks in your install routine for others going forward.
Thanks again and very much appreciate your time!!

E:\redmine4\apps\redmine\htdocs>bundle install --without development test postgresql sqlite --no-deployment
Fetching source index from https://rubygems.org/
Terminate batch job (Y/N)? y

E:\redmine4\apps\redmine\htdocs>bundle install --without development test sqlite --no-deployment
Fetching gem metadata from http://rubygems.org/.Retrying dependency api due to error (2/3): Bundler::MarshalError TypeError: incompatible marshal file format (can't be read) format version 4.8 required; 60.33 given
Retrying dependency api due to error (3/3): Bundler::MarshalError TypeError: incompatible marshal file format (can't be read)
        format version 4.8 required; 60.33 given

Retrying source fetch due to error (2/3): Bundler::HTTPError Could not fetch specs from http://rubygems.org/
Retrying source fetch due to error (3/3): Bundler::HTTPError Could not fetch specs from http://rubygems.org/
Could not fetch specs from http://rubygems.org/

E:\redmine4\apps\redmine\htdocs>bundle install --without development test sqlite
 --deployment
You are trying to install in deployment mode after changing your Gemfile. Run `bundle install` elsewhere and add the updated Gemfile.lock to version control.

You have added to the Gemfile:
* deface (>= 1.1.0)
* gemoji (~> 3.0.0)
* invisible_captcha
* slim-rails
* brakeman
* rubocop
* rubycritic
* slim_lint
* awesome_print
* better_errors
* binding_of_caller

E:\redmine4\apps\redmine\htdocs>cd bin

E:\redmine4\apps\redmine\htdocs\bin>bundle exec rake redmine:plugins:migrate NAME=additionals RAILS_ENV=production
(in E:/redmine4/apps/redmine/htdocs) rake aborted!
NameError: uninitialized constant Emoji
E:/redmine4/apps/redmine/htdocs/plugins/additionals/lib/additionals.rb:26:in `setup'
E:/redmine4/apps/redmine/htdocs/plugins/additionals/init.rb:43:in `block in <top (required)>'
E:/redmine4/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:426:in `instance_exec'
E:/redmine4/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:426:in `block in make_lambda'
E:/redmine4/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
E:/redmine4/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:606:in `block (2 levels) in default_terminator'
E:/redmine4/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:605:in `catch'
E:/redmine4/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:605:in `block in default_terminator'
E:/redmine4/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:199:in `block in halting'
E:/redmine4/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:513:in `block in invoke_before'
E:/redmine4/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:513:in `each'
E:/redmine4/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:513:in `invoke_before'
E:/redmine4/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:131:in `run_callbacks'
E:/redmine4/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.2/lib/active_support/reloader.rb:89:in `prepare!'
E:/redmine4/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/railties-5.2.2/lib/rails/application/finisher.rb:63:in `block in <module:Finisher>'
E:/redmine4/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/railties-5.2.2/lib/rails/initializable.rb:32:in `instance_exec'
E:/redmine4/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/railties-5.2.2/lib/rails/initializable.rb:32:in `run'
E:/redmine4/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/railties-5.2.2/lib/rails/initializable.rb:61:in `block in run_initializers'
E:/redmine4/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/railties-5.2.2/lib/rails/initializable.rb:60:in `run_initializers'
E:/redmine4/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/railties-5.2.2/lib/rails/application.rb:361:in `initialize!'
E:/redmine4/apps/redmine/htdocs/config/environment.rb:14:in `<top (required)>'
E:/redmine4/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/railties-5.2.2/lib/rails/application.rb:337:in `require'
E:/redmine4/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/railties-5.2.2/lib/rails/application.rb:337:in `require_environment!'
E:/redmine4/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/railties-5.2.2/lib/rails/application.rb:520:in `block in run_tasks_blocks'
E:/redmine4/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
Tasks: TOP => redmine:plugins:migrate => environment (See full trace by running task with --trace)


E:\redmine4\apps\redmine\htdocs\bin>bundle exec rake redmine:plugins:migrate NAME=additionals RAILS_ENV=production --trace
(in E:/redmine4/apps/redmine/htdocs)
** Invoke redmine:plugins:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
rake aborted!
NameError: uninitialized constant Emoji
E:/redmine4/apps/redmine/htdocs/plugins/additionals/lib/additionals.rb:26:in `setup'
E:/redmine4/apps/redmine/htdocs/plugins/additionals/init.rb:43:in `block in <top (required)>'
E:/redmine4/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:426:in `instance_exec'
E:/redmine4/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:426:in `block in make_lambda'
E:/redmine4/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
E:/redmine4/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:606:in `block (2 levels) in default_terminator'
E:/redmine4/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:605:in `catch'
E:/redmine4/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:605:in `block in default_terminator'
E:/redmine4/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:199:in `block in halting'
E:/redmine4/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:513:in `block in invoke_before'
E:/redmine4/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:513:in `each'
E:/redmine4/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:513:in `invoke_before'
E:/redmine4/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:131:in `run_callbacks'
E:/redmine4/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.2/lib/active_support/reloader.rb:89:in `prepare!'
E:/redmine4/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/railties-5.2.2/lib/rails/application/finisher.rb:63:in `block in <module:Finisher>'
E:/redmine4/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/railties-5.2.2/lib/rails/initializable.rb:32:in `instance_exec'
E:/redmine4/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/railties-5.2.2/lib/rails/initializable.rb:32:in `run'
E:/redmine4/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/railties-5.2.2/lib/rails/initializable.rb:61:in `block in run_initializers'
E:/redmine4/ruby/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
E:/redmine4/ruby/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
E:/redmine4/ruby/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
E:/redmine4/ruby/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
E:/redmine4/ruby/lib/ruby/2.3.0/tsort.rb:347:in `each'
E:/redmine4/ruby/lib/ruby/2.3.0/tsort.rb:347:in `call'
E:/redmine4/ruby/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
E:/redmine4/ruby/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
E:/redmine4/ruby/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
E:/redmine4/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/railties-5.2.2/lib/rails/initializable.rb:60:in `run_initializers'
E:/redmine4/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/railties-5.2.2/lib/rails/application.rb:361:in `initialize!'
E:/redmine4/apps/redmine/htdocs/config/environment.rb:14:in `<top (required)>'
E:/redmine4/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/railties-5.2.2/lib/rails/application.rb:337:in `require'
E:/redmine4/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/railties-5.2.2/lib/rails/application.rb:337:in `require_environment!'
E:/redmine4/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/railties-5.2.2/lib/rails/application.rb:520:in `block in run_tasks_blocks'
E:/redmine4/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `block in execute'
E:/redmine4/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `each'
E:/redmine4/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `execute'
E:/redmine4/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/rake-12.3.2/lib/rake/task.rb:214:in `block in invoke_with_call_chain'
E:/redmine4/ruby/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
E:/redmine4/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/rake-12.3.2/lib/rake/task.rb:194:in `invoke_with_call_chain'
E:/redmine4/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/rake-12.3.2/lib/rake/task.rb:238:in `block in invoke_prerequisites'
E:/redmine4/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/rake-12.3.2/lib/rake/task.rb:236:in `each'
E:/redmine4/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/rake-12.3.2/lib/rake/task.rb:236:in `invoke_prerequisites'
E:/redmine4/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/rake-12.3.2/lib/rake/task.rb:213:in `block in invoke_with_call_chain'
E:/redmine4/ruby/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
E:/redmine4/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/rake-12.3.2/lib/rake/task.rb:194:in `invoke_with_call_chain'
E:/redmine4/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/rake-12.3.2/lib/rake/task.rb:183:in `invoke'
E:/redmine4/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/rake-12.3.2/lib/rake/application.rb:160:in `invoke_task'
E:/redmine4/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/rake-12.3.2/lib/rake/application.rb:116:in `block (2 levels) in top_level'
E:/redmine4/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/rake-12.3.2/lib/rake/application.rb:116:in `each'
E:/redmine4/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/rake-12.3.2/lib/rake/application.rb:116:in `block in top_level'
E:/redmine4/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/rake-12.3.2/lib/rake/application.rb:125:in `run_with_threads'
E:/redmine4/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/rake-12.3.2/lib/rake/application.rb:110:in `top_level'
E:/redmine4/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/rake-12.3.2/lib/rake/application.rb:83:in `block in run'
E:/redmine4/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/rake-12.3.2/lib/rake/application.rb:186:in `standard_exception_handling'
E:/redmine4/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/rake-12.3.2/lib/rake/application.rb:80:in `run'
E:/redmine4/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
E:/redmine4/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/bin/rake:23:in `load'
E:/redmine4/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/bin/rake:23:in `<main>'

Tasks: TOP => redmine:plugins:migrate => environment

**Comment by alexandermeindl** [comment]
> Fetching source index from https://rubygems.org/
> Terminate batch job (Y/N)? y

If you cancel this, it cannot work. You have to get source index from https://rubygems.org/. If this is not working on your server instance, most likely it is a network problem (bitnami instance cannot connect to https://rubygems.org/)

I am not a bitnami nor a Windows guy, the rest is up do you ;)

**Comment by da2125** [comment]
Thanks for all your help and guidance. I will try to download the gems and install locally.

**Comment by alexandermeindl** [comment]
Redmine 3.4 is not longer supported by this plugin. Since a log period no more feedback was coming in close this issue.
